import 'package:flutter/material.dart';

List<dynamic> words = [
  ["FİİL", "İş", "Oluş", "Hareket", "Eylem", "Sözcük"],
  ["UYAK", "Şiir", "Dize", "Benzerlik", "Kafiye", "Ses"],
  ["SÖZLÜK", "Anlam ", "Kelime ", "Sözcük", "Açıklama", "Lügat"],
  ["OKKA", "Ağırlık", "Ölçü", "Birim", "Kilo", "Tartı"],
  ["KUŞBAKIŞI", "Harita", "Tepe ", "Yukarı", "Görmek ", "Kroki"],
  ["KÖK", "Sözcük", "Ek", "Yapım", "Çekim", "Kelime"],
  ["FABL", "Hayvan", "La", "Fontaıne", "Masal", "İnsan", "Hikâye"],
  ["ŞİİR", "Şair", "Mısra", "Dize", "Kıta", "Dörtlük"],
  ["ÖYKÜ", " Hikâye", "Kahraman", "Yazar", "Yer", "Kitap"],
  ["HAL EKİ", "Çekim eki", "-i hali", "-de hali", "-den hali", "-e hali"],
  ["YAPIM", "EKİ", "Ek", "Kelime", "Kök", "Türemiş ", "Yapı"],
  ["FİİLİMSİ", "Sıfat", "İsim", "Zarf", "Fiil", "Ek"],
  ["EŞ", "SESLİ", "Yazılış", "Okunuş", "Aynı", "Sözcük", "Sesteş"],
  ["ZIT", "ANLAM", "Karşıt", "Sözcük", "Örnek", "Birbirine", "Mana"],
  ["MECAZ", "Kelime", "Sözcük", "Gerçek Anlam", "Yan Anlam", "Terim"],
  ["ÖZNE", "Cümle", "İş", "Kişi", "Varlık", "Öge"],
  ["MASAL", "Olağanüstü", "Kahraman", "Yazar", "Keloğlan", "Kitap"],
  ["FAY", "Hat", "Deprem", "Kırılmak", "Sarsılmak", "İstanbul"],
  ["ÖNERİ", "Teklif", "Çözüm", "Yol", "Cümle", "İyi Olur"],
  ["VARSAYIM", "Olmamış", "Tut ki", "Farz et", "Diyelim", "Cümle"],
  ["ÖDEV", "Ders", "Çalışmak", "Okul", "Öğretmen", "Ev"],
  ["KÜSMEK", "Darılmak", "Kızmak", "Konuşmak", "Tartışmak", "Kavga"],
  ["AVİZE", "Lamba", "Kristal", "Tavan", "Işık", "Aydınlık"],
  ["KOORDİNAT", "Yer", "Enlem", "Boylam", "Belirtmek", "Vermek"],
  ["BASKÜL", "Tartı", "Kilo", "Ağır", "Ölçü", "Hafif"],
  ["HARABE", "Yıkık", "Eski", "Tarihi", "Efes", "Gezmek"],
  ["ÇAYLAK", "Acemi", "Deneyim", "Tecrübe", "Usta", "Yeni"],
  ["CEMRE", "Düşmek", "Hava", "Toprak", "Su", "Bahar"],
  ["HALÜSİNASYON", "Hayal", "Gerçek", "Görmek", "İllüzyon", "Serap"],
  ["ŞAMDAN", "Mum", "Işık", "Aydınlık", "Yakmak", "Süs"],
  ["TIRABZAN", "Merdiven", "Korkuluk", "İnmek", "Çıkmak", "Bina"],
  ["KORNİŞ", "Tavan", "Perde", "Asmak", "Pencere", "Cam"],
  ["NİHALE", "Altlık", "Tencere", "Çaydanlık" ",Sıcak", "Tezgâh"],
  ["DUY", "Tavan", "Lamba", "Işık", "İşitmek", "Anahtar"],
  ["ARMAĞAN", "Hediye", "Vermek", "Almak", "Doğum", "günü", "Sevindirmek"],
  ["KABZIMAL", "Meyve", "Sebze", "Hal", "Satmak", "Aracı"],
  ["PİŞMANLIK", "Hata", "Üzülmek", "Yanlış", "Keşke", "Son"],
  ["KUMBARA", "Para", "Biriktirmek", "Yatırım", "Banka", "Saklamak"],
  ["ANTİKA", "Müzayede", "Zengin", "Eski", "Tablo", "Tarihi"],
  ["SAĞDIÇ", "Damat", "Düğün", "Gelin", "Güvey", "Sırtına vurmak"],
  ["ADEM ELMASI", "Erkek", "Gırtlak", "Çıkıntı", "Boğaz", "Havva"],
  ["SATRANÇ", "Şah-Mat", "Kale", "Vezir", "Piyon", "Fil"],
  ["MANGALA", "Oyun", "Osmanlı", "Kuyu", "Taş", "Hazine"],
  ["PARAŞÜT", "Uçak", "Atlamak", "Uçmak", "Balon", "Hava"],
  ["BALMUMU", "Mum", "Erimek", "Heykel", "Müze", "Bal"],
  ["FERMUAR", "Pantolon", "Mont", "Giysi", "Kıyafet", "Kot"],
  ["KELEBEK", "Renkli", "Uçmak", "Tırtıl", "Koza", "Hayvan"],
  ["GÖKKUŞAĞI", "Renkli", "Hava", "Güneş", "Yağmur", "Ebem"],
  ["MALA", "İnşaat", "Duvar", "Usta", "Sıva", "Çimento"],
  ["TİYATRO", "Oyuncu", "Sahne", "Perde", "Oyun", "Suflör"],
  ["BAĞLAMA", "Türkü", "Müzik", "Saz", "Tel", "Akort"],
  ["DOST", "Güven", "Samimi", "Dürüst", "Arkadaş", "Ahlaklı"],
  ["DERGİ", "Gazete", "Mecmua", "Makale", "Yazı", "Kapak"],
  ["KAPAN", "Av", "Kurt", "Hayvan", "Tuzak", "Fare"],
  ["KEDİ", "Pati", "Fare", "Tüy", "Kuyruk", "Hayvan"],
  ["ANAHTAR", "Kilit", "Metal", "Kasa", "Kapı", "Çilingir"],
  ["EMPATİ", "Kendini", "Başkası", "Yerine", "Koyma", "Düşünme"],
  ["HOŞGÖRÜ" "Mevlana" "Anlayış" "Empati" "Ne olursan" "Gel"],
  ["KİŞİLEŞTİRME", "İnsan", "Fabl", "Hayvan", "Varlık", "Konuşturma"],
  ["ÖZÇEKİM", "Selfie", "Telefon", "Kendi", " Fotoğraf", "Poz"],
  ["ULEMA", "Bilgin", "Osmanlı", "Din", "Alim", "Hoca"],
  ["BONKÖR", "Eli Açık", "Cömert", "Para", "Gönlü Zengin", "Harcamak"],
  ["HEYBETLİ", "Yüce", "Dağ", "Büyük", "Yüksek", "İri"],
  ["ÇIRA", "Ateş", "Yakmak", "Odun", "Tahta", "Çay"],
  ["MANİ", "Kısa", "Şiir", "Edebiyat", "Sakız", "Engel"],
  ["FİDAN", "Ağaç", "Büyümek", "Küçük", "Orman", "Dikmek"],
  ["PRATİK", "Kolay", "Zekâ", "Çabuk", "Hızlı", "Çözüm"],
  ["KIVILCIM", "Ateş", "Kibrit", "Çakmak", "Taş", "Sürtmek"],
  ["MİSKİN", "Tembel", "Uyuşuk", "Yavaş", "Ağır", "Kedi"],
  ["MESAİ", "Saat ", "İş", "Fazla", "Akşam", "Kalmak"],
  ["KÜREMEK", "Kar", "Ev", "Yol", "Buz", "Kış"],
  ["KÖHNE", "Eski", "Tarihi", "Yıkılmak", "Bina", "Harabe"],
  ["YAYIK", "Ayran", "Su", "Yoğurt", "Çalkalamak", "Süt"],
  ["CİHAZ", "ürün", "makine", "küçük", "elektronik", "aparat"],
  ["İHİTYAÇ", "var", "zorunlu", "yemek", "su", "yaşam"],
  ["ANTROPOMETRİ", "ölçü", "insan", "uzunluk", "boyut", "beden"],
  ["REAKTÖR", "uranyum", "nükleer", "radyasyon", "santral", "çernobil"],
  ["PETROL", "benzin", "mazot", "yakıt", "akaryakıt", "otomobil"],
  ["BETON", "çimento", "inşaat", "gri", "duvar", "yapmak"],
  ["İLETİŞİM", "haberleşme", "telefon", "mesaj", "teknoloji", "bell"],
  ["TAMİR", "etmek", "onarmak", "bozulmak", "kırılmak", "usta"],
  ["GÜVENLİK", "korunmak", "tehlike", "iş", "yasa", "görevli"],
  ["SÜREÇ", "zaman", "döngü", "tasarım", "saat", "ilerlemek"],
  ["PROBLEM", "matematik", "sorun", "sıkıntı", "dert", "çözüm"],
  ["MALZEME", "ham madde", "araç", "gereç", "resim", "iş"],
  ["TASLAK", "çizim", "hayal", "kurgu", "tasarım", "geliştirme"],
  ["MODEL", "manken", "ürün", "yeni", "boyut", "maket"],
  ["PROTOTİP", "yapmak", "tasarlamak", "maket", "küçük", "ölçek"],
  ["GERİ DÖNÜŞÜM", "kağıt", "atık", "yeniden", "tekrar", "çevre"],
  [
    "BİLGİSAYAR DESTEKLİ TASARIM",
    "çizmek",
    "autocad",
    "tasarlamak",
    "el",
    "fare"
  ],
  ["OKUL", "eğitim", "öğretim", "burası", "öğretmen", "öğrenci"],
  ["JEOTERMAL", "su", "buhar", "sıcak", "yer altı", "magma"],
  ["IŞIK", "enerji", "güneş", "ampül", "aydınlatma", "led"],
  ["DALGA", "deniz", "enerji", "okyanus", "su", "sörf"],
  ["ZEMİN", "yer", "mimari", "temel", "fayans", "kat"],
  ["ÇATI", "ev", "korumak", "kiremit", "kat", "çeşit"],
  ["DUVAR", "beton", "yalıtım", "pencere", "tuğla", "bahçe"],
  ["ARAŞTIRMAK", "internet", "wikipedia", "dedektif", "bulmak", "sonuç"],
  ["KİMYASAL", "tepkime", "fen", "enerji", "sıvı", "deney"],
  ["DÖNÜŞÜM", "enerji", "santral", "dönmek", "yeni", "elektrik"],
  ["SINAV", "ders", "puan", "okul", "sınıf", "girmek"],
  ["RİTİM", "müzik", "tempo", "tasarım", "konu", "resim"],
  ["SES", "tel", "enerji", "müzik", "çımak", "konuşmak"],
  ["GRAFİK", "görsel", "tasarım", "konu", "pasta", "çizim"],
  ["ÇEVRE", "kirlilik", "doğa", "dünya", "çöp", "etraf"],
  ["KARBON", "atom", "monoksit", "zarar", "fabrika", "baca"],
  ["İKLİM", "doğa", "çevre", "mevsim", "değişiklik", "bölge"],
  ["TEMEL", "mimari", "inşaat", "ev", "taşıyıcı", "eleman"],
  ["FİSYON", "uranyum", "atom", "tepkime", "radyoasyon", "parçalanma"],
  ["HİDRO ELEKTRİK SANTRALİ", "enerji", "baraj", "atatürk", "su", "türbin"],
  ["RADYASYON", "nükleer,", "zararlı", "çernobil", "kanser", "ışın"],
  ["EDİSON", "ampül", "elektrik", "amerika", "ışık", "akşam"],
  ["MOTOR", "piston", "yakıt", "otomobil", "egzoz", "yanma"],
  ["ERGONOMİ", "rahat", "güvenli", "sağlıklı", "antropometri", "oturmak"],
  ["TASARIM", "dış görünüş", "fikir", "kurgu", "renk", "ürün"],
  ["TEKNOLOJİ", "ürün", "bilgisayar", "üretmek", "kolay", "yeni"],
  ["ENDÜSTRİ", "sanayi devrimi", "dört", "gelişmek", "yöntem", "üretim"],
  ["BULUŞ", "bilim insanı", "bulmak,", "deney", "bilim", "araştırma"],
  ["ROBOT", "kendi", "makina", "yapay zeka", "fabrika", "sophia"],
  ["HAYAT", "yaşam", "insan", "ömür", "zaman", "güzel"],
  ["MAKİNE", "üretim", "kas gücü", "hızlı", "kolay", "elektrik"],
  ["TÜBİTAK", "sergi", "fuar", "bilim", "4006", "yapmak"],
  ["PROJE", "not", "puan", "kontrol", "üretim", "tasarım"],
  ["ATÖLYE", "ders", "burası", "neresi", "teknoloji", "iş"],
  ["CETVEL", "ölçüm", "uzunluk", "boy", "matematik", "çizim"],
  ["MAKAS", "kağıt", "kesmek", "kumaş", "tasarım", "araç"],
  ["PAZARLAMA", "satış", "para", "ürün", "müşteri", "reklam"]
];
